# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sshkm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='superuser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
