# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sshkm', '0002_host_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='last_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
